### ISSUE TITLE
Alvar marker error message from drone_simulation

### ISSUE THREAD

**Issue by Moseskota** [mohamedsayed18/Drone_simulation#3]
Hello Mohammed. 

I have been trying to reproduce the drone_simulation project. But I am facing the **from ar_track_alvar_msgs.msg import AlvarMarkers
ModuleNotFoundError: No module named 'ar_track_alvar_msgs'**  . but nothing is given in the source folder about AlvarMarkers. Can you please tell me how to make the working?.

I am using ROS noetic.

**Comment by mohamedsayed18** [comment]
The project was done with melodic, I'm not sure if ar_track_alvar package is available for noetic
You can check this repo https://github.com/ros-perception/ar_track_alvar it may be helpful
Check this [answer](https://github.com/ros-perception/ar_track_alvar/issues/82#issuecomment-893859329) too
